### ISSUE TITLE
This color-picker JS lib not work with your CDN files - See Web Dev Console Attached

### ISSUE THREAD

**Issue by unixneo** [nhnent/tui.color-picker#12]
Hi.

I have installed from the CDN and locally; and each time I get the error:

![screen shot 2019-01-20 at 4 47 21 pm](https://user-images.githubusercontent.com/12891828/51437630-633b0400-1cd3-11e9-9016-c67560696c64.png)

Why does this color-picker JS lib not work with the CDN files you specify?

**Comment by jung-han** [comment]
Hi @unixneo
We are not including dependency files in th cdn.
If you want to use it via CDN, please add the tui-code-snippet.

Because of this, we recommend using npm.
Anyway, here's an example.

```html
<head>
  <script src="https://uicdn.toast.com/tui.code-snippet/latest/tui-code-snippet.js"></script>
  <script src="https://uicdn.toast.com/tui-color-picker/latest/tui-color-picker.js"></script>
  <link rel="stylesheet" type="text/css" href="https://uicdn.toast.com/tui-color-picker/latest/tui-color-picker.css">
</head>
<body>
<div id="test"></div>
<script>
  const container = document.getElementById('test');
  const instance = tui.colorPicker.create({
      container: container,
  });
</script>
</body>
```

Thanks.
